path: ~/Dev/b/yolo/lab5-dat301m-dataset-praparing/ # absolute path to dataset
test: lab5-dat301m-dataset-praparing/train/images # relative path to test images
train: lab5-dat301m-dataset-praparing/train/images # relative path to training images
val: lab5-dat301m-dataset-praparing/val/images # relative path to validation images

# classes
names:
  0: cat